version: "3.9"
services:
  be:
    image: fw-maintenance-be:latest
    build: ./api_server
    volumes:
      - /home/workspace:/home/workspace
    network_mode: "host"

  fe:
    image: nginx:latest
    ports: ["2080:80"]
    volumes:
      - ./fe/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./fe/dist:/usr/share/nginx/html
